# Generated by Django 4.1.7 on 2023-03-30 09:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="emg_contact",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="KR"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="KR"
            ),
        ),
    ]
