# Generated by Django 4.1.7 on 2023-04-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_profile_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoequipment",
            name="name",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
