# Generated by Django 4.1.7 on 2023-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_videoequipment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="PositionChoices",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "관리자"),
                    (1, "조사단장"),
                    (2, "책임조사원"),
                    (3, "조사원"),
                    (4, "준조사원"),
                    (5, "보조원"),
                    (6, "근로자"),
                    (7, "직원"),
                ],
                default=7,
            ),
        ),
    ]
