# Generated by Django 4.1.7 on 2023-04-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_profile_positionchoices"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="PositionChoices",
            new_name="position",
        ),
    ]
