# Generated by Django 4.1.7 on 2023-03-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("dig_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workhistory",
            name="images",
            field=models.ManyToManyField(blank=True, to="common.image"),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="zone",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
